// app/layout.tsx
import type { Metadata } from 'next'
import { Cinzel, Poppins } from 'next/font/google' // Import fonts
import './globals.css'

// Configure fonts
const cinzel = Cinzel({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'], // Specify needed weights
  variable: '--font-cinzel', // CSS Variable name
})

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['400', '700'], // Specify needed weights
  variable: '--font-poppins', // CSS Variable name
})

export const metadata: Metadata = {
  title: 'My Blog', // Default title, can be overridden
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      {/* Apply font variables to the body or html tag */}
      <body className={`${cinzel.variable} ${poppins.variable} font-body`}>
        {/* Set default body font */}
        {children}
      </body>
    </html>
  )
}